/// Who sent a message.
public enum Role: String, Codable {
    /// The assistant sent the message.
    /// 
    /// Messages marked with `role: .assistant` are not always generated by a model. See <doc:Request#messages>.
    case assistant

    /// The user sent the message.
    case user
}